module Capitalizable
  extend ActiveSupport::Concern

  # Calculates the absolute profit generated by this asset (Revenue - Cost).
  def absolute_profit(revenue, cost)
    revenue - cost
  end

  # Calculates the annualized rate of profit, factoring in the velocity of the transaction.
  # This is crucial: a small margin turned over daily results in a massive annualized rate.
  #
  # @param revenue [Numeric] The final sale price or total rent collected
  # @param cost [Numeric] The initial capital employed to acquire/produce the asset
  # @param duration_in_days [Integer] The time it took to complete the transaction cycle
  def annualized_rate_of_profit(revenue, cost, duration_in_days)
    return 0 if cost.zero? || duration_in_days.zero?

    absolute_margin = (revenue - cost).to_f / cost
    turnovers_per_year = 365.0 / duration_in_days

    absolute_margin * turnovers_per_year
  end
end
